package server

//nolint:gci
import (
	"context"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	ginprometheus "github.com/zsais/go-gin-prometheus"

	"github.com/rodziievskyi-maksym/grn-subscription-service/internal/config"
	"github.com/rodziievskyi-maksym/grn-subscription-service/internal/delivery/handler"
	"github.com/rodziievskyi-maksym/grn-subscription-service/internal/infrastructure/server/middleware"

	// docs are generated by Swag CLI, you have to import it.
	_ "github.com/rodziievskyi-maksym/grn-subscription-service/docs"
)

type Server struct {
	server *http.Server
}

// NewHTTPServer
// @title           GitHub Release Notifier API
// @version         1.0
// @description     API Server for monitoring GitHub releases and notifying users.
// @host            localhost:8080
// @BasePath        /
func NewHTTPServer(sh *handler.SubscriptionHandler, cfg *config.Config) *Server {
	if cfg.IsProduction() {
		gin.SetMode(gin.ReleaseMode)
	}

	router := gin.Default()
	_ = router.SetTrustedProxies([]string{"127.0.0.1"})

	prometheusMiddleware := ginprometheus.NewPrometheus("gin")
	prometheusMiddleware.Use(router)

	router.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "UP"})
	})

	router.StaticFile("/home", "./web/index.html")

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

	api := router.Group("/api/v1").Use(middleware.APIKeyAuth(cfg.APIKey))
	api.POST("/subscribe", sh.Subscribe)
	api.DELETE("/unsubscribe", sh.Unsubscribe)
	api.GET("/subscriptions", sh.GetSubscriptions)

	httpServer := &http.Server{
		Addr:              cfg.ServerAddress(),
		Handler:           router,
		ReadHeaderTimeout: 5 * time.Second,
	}

	return &Server{
		server: httpServer,
	}
}

func (s *Server) Run() error {
	return s.server.ListenAndServe()
}

func (s *Server) Shutdown(ctx context.Context) error {
	return s.server.Shutdown(ctx)
}
